#!/usr/bin/env nextflow

/*
 * Use MultiQC (v1.28) to perform simultaneous visualization of short- and long-read quality before and after processing
 */
process multiQC {

    conda 'bioconda::multiqc==1.28'
    
    publishDir "${params.batch}/${outdir}", mode: 'copy'

    input:
        path input_files
        val outdir

    output:
        path "multiqc_report.html"
        path "*_data"
    
    // This script gathers the quality information generated by fastp and fastplong for each .fastq or pair of .fastq files, then structure it in a way where all of it is viewable in one condensed report (note - this will lack some information or visuals from some of the QC tools!)
    script:
    """
    multiqc --fn_as_s_name .
    """
}
