#!/usr/bin/env nextflow

/*
 * Default testing parameters
 */
params.batch = 'test_results'
params.srdir = "/srv/dev/denovo_assembly_pipeline/data/short_read"
params.samples = "/srv/dev/denovo_assembly_pipeline/test-samples.csv"

// Include modules
include { shortTrim as shortTrim1} from "./modules/shortTrim.nf"

/*
 * Use MultiQC (v1.28) to perform simultaneous visualization of short- and long-read quality before and after processing
 */
process multiQC {

    conda 'bioconda::multiqc==1.28'
    
    publishDir "${params.batch}/${outdir}", mode: 'copy'

    input:
        path input_files
        val outdir

    output:
        path "multiqc_report.html"
        path "*_data"
    
    // This script gathers the quality information generated by fastp and fastplong for each .fastq or pair of .fastq files, then structure it in a way where all of it is viewable in one condensed report (note - this may lack some information or visuals from some of the QC tools!)
    script:
    """
    multiqc --fn_as_s_name .
    """
}

workflow {

    // Create a channel for sample information
    samples_ch = Channel.fromPath(params.samples)
                        .splitCsv( skip: 1 )

    // Run fastp trimming and QC, then place outputs into individual directories
    outdir = '0-short_trim'
    shortTrim1(params.srdir, samples_ch, outdir)

    // Run MultiQC report generation, then place reports into a general directory
    outdir = '0-multiQC_report'
    multiQC(shortTrim1.out.fpjson.collect(), outdir)
}
